---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lodestar-frontend
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "deployment"
    repoURL: "https://github.com/rht-labs/lodestar-frontend.git"
    targetRevision: "master"
    helm:
      values: |
        imageTag: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
